### PR TITLE
Summary for sponsors to see how many attendees attended each event #171

### PR DESCRIPTION
**Pull request by smandekar1**
Created PR that tabulates and displays RSVPs from the past year.

### CODE REVIEW

**Comment by raymondberg** [comment]
I think this needs to get rebased to address the SponsorGroups change

**Comment by smandekar1** [comment]
Screen Shot 2019-11-27 at 1 41 03 PM

**Comment by elmq0022** [comment]
Looks pretty good to me.  However would the total be better on the past
meetings page and/ or the front page?

**Comment by smandekar1** [comment]
Good.  I think it should go on the sponsors page and it can go on those pages too.

**Comment by elmq0022** [comment]
Sam, allow me to make my case.  As I believe we would both like to have
more chipy sponsorship.

First adding the attendance to the past meetings page fits as this is a
meeting detail.

If a user of the site is interested in past meeting topics, sponsorship,
and attendance, the meeting page is a natural and intuitive way to discover
this related information.  This task seems to be complete.

Putting the information on the front page is a nice bragging item and
easily discovered because the front page is where most everyone lands
(sponsors included).  Also we put the current meeting there.  So, we can
say hey look we have this cool meeting coming up and lots of people attend
our meetings.

I feel the number of meeting attendees is not directly related to the
sponsor details, i.e it's not grouped with sponsor tier, industry, length
of sponsorship, etc.

I feel we should keep the site as intuitive to develop as possible as many
other people are likely to contribute to chipy.org.

Back to sponsorship,  I personally don't believe adding the number of
attendees to the sponsor list will equal increased sponsorship.

Please let me know what you think.  I am happy to discuss at our next
meeting.  Hopefully others opine as well.  😁

**Comment by smandekar1** [comment]
let's discuss it.  more sponsorship seems like the goal. The original issue was from Joe https://github.com/chicagopython/chipy.org/issues/171 and that's what I was trying to create or replicate

**Comment by smandekar1** [comment]
Is this all set?  

I'm not going to look into other marketing metrics that can be added in different areas of the site at this point.  I'm just going to do this one.

**Comment by elmq0022** [comment]
I approve :hamburger:

**Comment by raymondberg** [comment]
Merged with 9d3c614551821358280d054f11f7900983961709

**Pull request closed without merging**
