### PR TITLE
WIP - used safe template filter

### PR DESCRIPTION
**Pull request by sundance14**
Team Members:
Loren Velasquez: https://github.com/rebeldroid12
Manali Walke: https://github.com/manaliwalke
Sam Mahisekar https://github.com/smandekar1
Kevin Shin: https://github.com/sundance14

### CODE REVIEW

**Comment by raymondberg** [comment]
@sundance14 @rebeldroid12 @manaliwalke @smandekar1 We'd love to see you push this across the finish line! Will anyone take up the torch?

**Comment by smandekar1** [comment]
I'll go for it. Will add safe filter to meeting description

**Comment by smandekar1** [comment]
couldn't amend this pull request so created a new one which fixes issue

**Comment by raymondberg** [comment]
This is a first attempt at #167

**Pull request closed without merging**
