### PR TITLE
Upcoming meeting view

### PR DESCRIPTION
**Pull request by jalletto**
Here's a first draft for this issue.

### CODE REVIEW

**Comment by JoeJasinski** [comment]
I think this will be a nice feature.  I wonder if it would make sense to link this on the existing past meetings page.  For example, the past meetings page and the upcoming meetings page look almost exactly the same.  If we had one page that said "Past Meetings | Upcoming Meetings | Recent Topics" it could put all related meeting queries in one place. More specificially, we could combine the following two pages:

http://localhost:8000/meetings/upcoming/
Screen Shot 2019-07-01 at 8 19 24 PM

http://localhost:8000/meetings/past/
Screen Shot 2019-07-01 at 8 09 50 PM

**Comment by raymondberg** [comment]
@jalletto We're picking up PRs again, are you up to incorporate Joe's suggestion?

**Comment by jalletto** [comment]
Yes, absolutely. I'll take a look at it tomorrow when I have some more time.

**Comment by raymondberg** [comment]
We're still rooting for you @jalletto! 

rooting for ya

**Comment by raymondberg** [comment]
I'm going to close this one for now, but we'd love to have you open later if you get time! Thanks again for working on it!

**Pull request closed without merging**
