### PR TITLE
Feature/reviewer

### PR DESCRIPTION
**Pull request by CarlFK**
Reviewer role is someone who gets the dubious privilege to watch the video from start to finish and decide if it is good enough or needs fixing. 
more:   https://github.com/CarlFK/veyepar/wiki/Reviewer

This PR should be enough so that an admin can put the data in the database using the admin UI, and the export exports it.

sad confession: it is untested.  I hope it works.

### CODE REVIEW

**Comment by raymondberg** [comment]
From an organizational perspective, it feels like this would be easier to manage if this were always the same person on our side rather than putting it in the hands of many (3 speakers x 12 months = 36 reviewers per year). Is there a specific reason to have this per-talk?

**Comment by CarlFK** [comment]
it is the crowd sourcing model.  spread the work out, and to people that want to do the work for reasons other than "someone needs to do this work."  

from https://github.com/CarlFK/veyepar/wiki/Reviewer

**More fluff: I want to emphasize that each reviewer should only be responsible for one talk. The reviewer only has one job: to catch any mistakes that might happen to this one video. This one video should get their complete attention. "All the videos" is an unreasonable task as it requires discovering what the actual set of videos is....**

I can CC one or more people on all of this, and if someone else gets to it first, that's fine.  There shouldn't be the problem of 2 people doing the same 'work' because it shouldn't be work, it should be a bunch of people watching the same video, which is kinda the goal of making these videos: 1000's of people watching them. 

@WeepingClown13 (Ananthu, Debian video team) has offered to watch all the videos.  I like this, but I also don't.  Someday it will be a task that they are obligated to do that they don't really want to do, and they are not getting any benefit, other than having access to videos a day earlier, which isn't really 'value'.  It's barely prestige.  I feel it is taking advantage of someone's generosity, and that's something we should all try to avoid.

**Comment by WeepingClown13** [comment]
Both makes sense to me, but yes, having more people always pays out. For one the result doesn't just depend on a single person that way, and the person will not find it a "job" either. To backup what Carl said, I agreed to review one of the recent videos and then got tied to the bed with a fever, only to find out later someone else already did the job and approved the video, which worked out in everyone's favor.

**Comment by raymondberg** [comment]
Edit: Alternatively, if it's just email we can also send it to a distribution list. We have a speakers-guild email distro that we coordinate speakers on already. The same group could be responsible for reviewing. Let me know if that's preferable.

**Comment by CarlFK** [comment]
come to holiday club tomorrow wednesday, 6-9pm.  we will get this figured out.  and auth to sensitive info too.

**Comment by raymondberg** [comment]
This was resolved with https://github.com/chicagopython/chipy.org/pull/518

**Pull request closed without merging**
