### PR TITLE
Feature/django18

### PR DESCRIPTION
**Pull request by JoeJasinski**
I think I have Django 1.8 updates about ready to go, but I could use some code review.  I've added more information in the ticket below. https://github.com/chicagopython/chipy.org/issues/102

### CODE REVIEW

**Comment by emperorcezar** [comment]
:+1:

**Comment by JoeJasinski** [comment]
Hey all, since this branch was ready to merge, it appears that there have been some new features added that include database migrations.  I've tried merging them in now, but am testing currently.

**Comment by JoeJasinski** [comment]
@emperorcezar, @tanyaschlusser, @tathagata 

I think I've merged in the changes successfully.  I've pushed them to my dev site below.   I wouldn't mind a second pair of eyes on the changes.  

http://chipy-dev.herokuapp.com/

Note that since I don't own the heroku test domain below, I don't think I can get Google social auth to work with it without configuring a new domain for it.   If you'd like admin access, let me know and I can create you an account.

**Comment by brianray** [comment]
@emperorcezar  we need an update on this ASAP

**Comment by emperorcezar** [comment]
@brianray Please explain reasoning for ASAP?

Otherwise, feel free to test and provide a thumbs up.

@JoeJasinski What exactly do you need to test Google Social Auth?

**Comment by JoeJasinski** [comment]
Hi @emperorcezar, 

There is some other enhancements to the site that other members have expressed interest in doing.  It would be nice to deploy this soon so we could base that work off of Django 1.8.  The pull request has been about ready to merge for a bit sand I was hoping for a second look from someone.  T mentioned he might also try to spin up the new 1.8 branch for testing.  

Regarding the social auth, I'm not sure how to test that without setting up a new test domain and verifying that domain (since we don't own *.herokuapp.com, I'm not sure how to verify).  If you know a simpler way to get social auth working for Dev, I'd be glad to try.  However, I'm sure Django social auth works with Django 1.8, so I'd been testing with just a standard login thinking that it would probably be ok.

**Comment by JoeJasinski** [comment]
@tathagata, regarding the interval field, when we tried to the master branch the other day, I think we found the new interval field version that you mentions to install cleanly.  I didn't encounter any issues when I last tried to install the 1.8 branch, but it's possible that something has changed since. If we hit issues with that package, bumping the version might fix.

**Comment by emperorcezar** [comment]
@JoeJasinski You can test (at least you use to) by setting your host to point chipy.org at your local machine and running runserver on port80. You can use the heroku toolbelt to pull down the keys were using.

**Comment by emperorcezar** [comment]
Pushed to production.

**Comment by tathagata** [comment]
:+1:

**Comment by JoeJasinski** [comment]
Awesome!

**Pull request merged**
