### PR TITLE
Django upgrade to 1.11

### PR DESCRIPTION
**Pull request by elmq0022**
Upgrades to various packages and gets us on django 1.11.  

Will do some further testing over the next few days but seems okay with some preliminary testing.

### CODE REVIEW

**Comment by elmq0022** [comment]
I'll continue to do some more testing of the site functionality locally, but right now I don't anticipate any issues.

**Comment by sophm256** [comment]
@elmq0022
As requested, these are tests done on your 1.11 branch that have the latest commits of sponsor logo tests.

**These are the things that I tested that were fine:**
- created sponsor groups,  sponsors, and general sponsor and checked the sponsor list page as well as sponsor detail.
- Added .png and .jpg logos that show up on sponsor list, sponsor detail, and homepage

- created main and non main meetings that show up on homepage
- tested custom titles for main and non main meetings

- created venue, meeting types, presentor

- tested flatpage by creating one for 'sigs' page

- created announcement object, which showed on 'homepage' and also on 'announcements' page

- In navbar of homepage, I clicked on 'speak' link, which takes you to form where you can fill out if you want to propose a talk. I filled out this form and pressed the submit button. After clicking the submit button, it redirected to the 'homepage' with a success message 'topic has been submitted'. It also created two objects: a 'presentor' object and 'topic' object which you can see in the admin page.

- clicked through 'sign up' link for the mailing list on 'contact page'


**ERRORS:**

**1) Flatblock Errors**

- I successfully added flatblock 'sponsor_info_text' object through admin page. But when I went to the sponsor list page, I encountered a TypeError. I have attached two files showing this error.   

- I decided to test a flatblock for a different page to see if I could reproduce the flatblock error.
I created flatblock 'homepage_welcome_text' in admin page.  It's flatblock that's supposed to show up on homepage in the 'about' section. When I visited the homepage, I got the similar error of 'typeerror at /" , "context must be a dict rather than a RequestContext."

**2) Error after trying to submit contact email**
I went to the 'contact' page and filled out the contact form. (The backend settings for the email is the console.) After pressing submit button, I got an error message "ModuleNotFoundError at /contact/". I have attached a pic show this error below.

**3) Error I previously talked about before.** There's a 'Recursion error' when going to the admin page and trying to add 'topic' object.

**NOT AN ERROR BUT SOMETHING TO THINK ABOUT:**
-In the 'announcement' model, there is an imagefield. When I was making an 'announcement' object, I was able to successfully add an .jpg through in the admin page. But if you look at the template 'announcements/past_announcements.html', an image is not coded into to it. Considerations: Should there be an imagefield (or thumbnail) coded into template page? Or should the imagefield be removed from the announcment model, since it's not being used?  

........................................................................................................................

**Results of  running 'make test'** 
There were 31 tests that passed (including the new logo tests you just implemented), and there was one warning.

This is the warning:

chipy_org/apps/announcements/tests.py::SmokeTest::test__announcements_list_url__GET
  /home/app/.local/lib/python3.6/site-packages/tinymce/views.py:11: DeprecationWarning: Support for Django < 2.0 will be removed soon,please upgrade your projects to use Django 2.0
    "please upgrade your projects to use Django 2.0", DeprecationWarning)

......................................................................................................................

**Result of running 'make lint' :**
Your code has been rated at 10.00/10
...................................................................................................................

**Pictures of Errors:**
 
**Type-error-after-adding-flatblock**

type-error-after-adding-flatblock1

..........................................................................................................................................................

**Type-error-after-adding-flatblock (continued)**

type-error-after-adding-flatblock2

..........................................................................................................................................................

**Module-not-found-error-after-submitting-contact-email**

module-not-found-error-after-submitting-contact-email

**Comment by elmq0022** [comment]
Thanks for the comprehensive testing.  I will look into those more before
we deploy.

I may need to update the flatblocks package. You could give that a try if
you have time.  We should add a test for that as this is an error, but the
test suite passes.

**Comment by sophm256** [comment]
No problem. ☕️

**Comment by elmq0022** [comment]
@sophm256 good catch on the sponsor list error.  It's a straight forward and documented fix. Will push it in a couple days.

**Comment by sophm256** [comment]
I saw this issue online documenting flatblock issue on Django1.11. Are the 2 fixes the commits in this pull request? https://github.com/jazzband/django-flatblocks/pull/20  . This fixes it because the render function or render_to_string function wants a regular Python dictionary rather than a context as discussed in this thread https://stackoverflow.com/questions/43787700/django-1-11-typeerror-context-must-be-a-dict-rather-than-context

**Comment by elmq0022** [comment]
That looks correct to me.  Good catch.

I will upgrade the library and hopefully that addresses the issue.

Also, I will added some tests to exercise the flat blocks package.

I also have a few ideas to improve our deploys. I will keep you posted.

**Comment by sophm256** [comment]
Looking forward to hearing your ideas on how to improve the deploys.

**Comment by elmq0022** [comment]
Okay.  The upgrade to 1.11 should be good to go.  Thanks to @sophm256 for her nice work testing.  We also have two additional tests in our test suite.

**Comment by sophm256** [comment]
Thanks @elmq0022 for putting so much effort into getting the code base to where it needs to be.

**Pull request merged**
