### PR TITLE
Create upcoming events page that uses train stop timeline

### PR DESCRIPTION
**Pull request by sophm256**
I created an upcoming events page that uses a "train stop" timeline interface as outlined by issue #359.

-If there are two or more future events, then only one past event is shown. 
-If there's one or less future events, then two past events are shown.
-Pictures below show what it looks like in desktop mode.
-There's also a picture that shows what it looks like when screensize is less than 731px. All of the nodes switch to one side.
-Only future events have an 'RSVP' button
-Both 'RSVP' button and the blue linked 'title' for each node goes to the same meeting detail page.

-Max of 2 past events shown.
-Max of 5 future events shown.

-The red button 'See More Events' leads to all upcoming current events page.

TOP PIC OF DESKTOP MODE
train-timeline-top

BOTTOM PIC OF DESKTOP MODE
train-timeline-bottom

WHAT IT LOOKS LIKE  ON SCREENS LESS THAN 731 PX
screens-less-than-731px

### CODE REVIEW

**Comment by sophm256** [comment]
It says I have a merge conflict, please let me know what I should do to resolve it.

**Comment by sophm256** [comment]
What it looks like one phones smaller than 413px. I've removed the triangles from the sides of the nodes because there's not enough space for them.

small-phone1

**Review by raymondberg — APPROVED** [review]
First off: this is absolutely amazing. Really awesome work on this, it's everything I hoped it would be. 🍔 

Secondly, I apologize! I accidentally pushed commits I meant for my branch (https://github.com/sophm256/chipy.org/compare/train-track-page...raymondberg:train-track-page?expand=1) to yours. I reset yours, but if you see anything odd, it's my fault! 😿 

Third, on the branch above I have 1 substantive change (the very last commit) and the rest of it is just refactors I'd propose as I worked my way through the styles. I learn best by refactors! :D You could absolutely merge without incorporating any of my commits and I would still be extremely happy.

Finally, I'm happy to do a rebase with you, but I think this should be an easy rebase if you try `git checkout main && git pull origin main && git checkout train-track-page && git rebase -i main` and follow the on-screen instructions locally. That said, I would recommend incorporating or rejecting my commits prior to doing that. The conflict on main is pretty trivial. It should go quick.

**Comment by sophm256** [comment]
@raymondberg Really nice work with refactoring the code. As I mentioned, I merged your code into this branch. I appreciate the review and help with the rebase. :star::star::star::star:

**Comment by sophm256** [comment]
Here's what it looks like with after Ray's suggestion of making the text on the inactive nodes lighter (although Ray would prefer to be lighter than this.) :smile:

fade-of-inactive-text

**Comment by sophm256** [comment]
I added some CSS and HTML code for x-small phones that have screen sizes less than 371px. Notice the RSVP button has moved from the right of the node to the bottom of the node. I think this will probably be the last breakpoint in terms of screen sizes.

screens-less-than-371px

**Comment by sophm256** [comment]
I changed the background to white and reimplemented it so that you can have shadows around the entire node. 

white-background-with shadow-node

**Comment by raymondberg** [comment]
Cemile has approved with:

```Awesome solution [Sophan].```

**Pull request merged**
