### PR TITLE
Decouple Bootstrap CSS from site css

### PR DESCRIPTION
**Pull request by raymondberg**
__Problem__

Years ago we merged all of the bootstrap CSS into one big monstrosity of
a CSS file. In it we then modified core bootstrap configurations to make
our site look as absolutely amazing as it does now. This meant that
upgrading bootstrap would be like performing open-heart monster surgery.

__Solution__

No more! Perform one round of surgery to remove the chipy-specific CSS
from Bootstrap internals ahead of a possible upgrade from bootstrap.

We don't think this change is going to be perfect. There will be some
minor differences, but we did do some work to ensure the home page
didn't have significant style differences. Given our desire to get on
latest bootstrap and to redesign the site, it's worth breaking a few
eggs.

### CODE REVIEW

**Comment by raymondberg** [comment]
Co-edited by @sophm256 and me.

**Comment by elmq0022** [comment]
Current
Screenshot_2020-12-11_11-19-14

Proposed
Screenshot_2020-12-11_11-21-56

Personally I find the grey color hard to read against the grey background.  Is there an easy change?

**Review by elmq0022 — APPROVED** [review]
Nice update @raymondberg  and @sophm256.  Please see my comment in the discussion. :hamburger:

**Comment by sophm256** [comment]
@elmq0022 The issue with the grey text has been fixed by Ray and I.

**Pull request merged**
