### PR TITLE
Issue #183 - Add Code of Conduct to talk proposals

### PR DESCRIPTION
**Pull request by raymondberg**
## Problem

We need presenters to know about our Code of Conduct and ensure they know they need to abide by it.

## Solution

Add abbreviated callouts to the legal language about speaker agreement and talk releases.

### Screenshot

Screenshot 2019-03-31 17 58 37

### CODE REVIEW

**Comment by JoeJasinski** [comment]
Perhaps we can link this to our existing code of conduct on github? Or use the CMS to add the content. That way we can make editorial changes without having a PR.

**Comment by raymondberg** [comment]
I thought about that, but it felt like nobody would click it. Like a EULA.

**Comment by JoeJasinski** [comment]
If you use the flatblocks application (already installed), you can just add a placeholder for text. It would display the same was as pictured but we could have the text stored in the CMS. We currently use it in several places on the site, include the speaker submission page.

**Comment by JoeJasinski** [comment]
Here's an example:
https://github.com/chicagopython/chipy.org/blob/master/chipy_org/apps/meetings/templates/meetings/propose_topic.html#L17

**Comment by raymondberg** [comment]
Verrrrry nice. Awesome, I'll check it out!

**Comment by raymondberg** [comment]
Nice, merging since comments were incorporated!

**Pull request merged**
